-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.announcements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  class_id uuid,
  author_id uuid,
  title text NOT NULL,
  body text,
  week_start date,
  is_public boolean NOT NULL DEFAULT true,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT announcements_pkey PRIMARY KEY (id),
  CONSTRAINT announcements_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id),
  CONSTRAINT announcements_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT announcements_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id)
);
CREATE TABLE public.assessments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  class_id uuid,
  student_id uuid,
  title text NOT NULL,
  description text,
  subject text,
  grade USER-DEFINED,
  score numeric,
  max_score numeric CHECK (max_score IS NULL OR max_score > 0::numeric),
  assessed_by uuid,
  assessed_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT assessments_pkey PRIMARY KEY (id),
  CONSTRAINT assessments_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id),
  CONSTRAINT assessments_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT assessments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT assessments_assessed_by_fkey FOREIGN KEY (assessed_by) REFERENCES public.users(id)
);
CREATE TABLE public.attendance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  class_id uuid,
  student_id uuid,
  date date NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'present'::attendance_status,
  notes text,
  recorded_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT attendance_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id),
  CONSTRAINT attendance_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT attendance_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT attendance_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.users(id)
);
CREATE TABLE public.audit_changes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  table_name text NOT NULL,
  record_id uuid NOT NULL,
  operation text NOT NULL,
  old_values jsonb,
  new_values jsonb,
  changed_by uuid,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  ip_address inet,
  user_agent text,
  session_id text,
  CONSTRAINT audit_changes_pkey PRIMARY KEY (id),
  CONSTRAINT audit_changes_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id),
  CONSTRAINT audit_changes_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.users(id)
);
CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  user_id uuid,
  action text NOT NULL,
  object_type text,
  object_id uuid,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id),
  CONSTRAINT audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.class_memberships (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  class_id uuid NOT NULL,
  user_id uuid NOT NULL,
  membership_role USER-DEFINED NOT NULL DEFAULT 'teacher'::membership_role_type,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT class_memberships_pkey PRIMARY KEY (id),
  CONSTRAINT class_memberships_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT class_memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT class_memberships_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id)
);
CREATE TABLE public.classes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  name text NOT NULL,
  code text,
  created_by uuid,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT classes_pkey PRIMARY KEY (id),
  CONSTRAINT classes_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id),
  CONSTRAINT classes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.daily_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  class_id uuid,
  student_id uuid,
  kind USER-DEFINED NOT NULL DEFAULT 'note'::daily_log_kind,
  value text,
  rating smallint CHECK (rating IS NULL OR rating >= 1 AND rating <= 5),
  recorded_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  public boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  note text,
  CONSTRAINT daily_logs_pkey PRIMARY KEY (id),
  CONSTRAINT daily_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id),
  CONSTRAINT daily_logs_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT daily_logs_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT daily_logs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.device_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  provider text NOT NULL,
  token text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT device_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT device_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  class_id uuid,
  title text NOT NULL,
  description text,
  start_at timestamp with time zone NOT NULL,
  end_at timestamp with time zone,
  location text,
  created_by uuid,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id),
  CONSTRAINT events_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT events_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.guardian_students (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  guardian_id uuid NOT NULL,
  student_id uuid NOT NULL,
  relation text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT guardian_students_pkey PRIMARY KEY (id),
  CONSTRAINT guardian_students_guardian_id_fkey FOREIGN KEY (guardian_id) REFERENCES public.users(id),
  CONSTRAINT guardian_students_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT guardian_students_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id)
);
CREATE TABLE public.health_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  class_id uuid,
  student_id uuid NOT NULL,
  type USER-DEFINED NOT NULL,
  recorded_at timestamp with time zone NOT NULL DEFAULT now(),
  temperature_celsius numeric CHECK (temperature_celsius IS NULL OR temperature_celsius >= 30::numeric AND temperature_celsius <= 45::numeric),
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes text,
  severity smallint CHECK (severity IS NULL OR severity >= 1 AND severity <= 5),
  recorded_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT health_logs_pkey PRIMARY KEY (id),
  CONSTRAINT health_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id),
  CONSTRAINT health_logs_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT health_logs_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT health_logs_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.users(id)
);
CREATE TABLE public.invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  email USER-DEFINED NOT NULL,
  role USER-DEFINED,
  token text NOT NULL UNIQUE,
  created_by uuid,
  accepted_by uuid,
  accepted_at timestamp with time zone,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT invitations_pkey PRIMARY KEY (id),
  CONSTRAINT invitations_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id),
  CONSTRAINT invitations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT invitations_accepted_by_fkey FOREIGN KEY (accepted_by) REFERENCES public.users(id)
);
CREATE TABLE public.menus (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  class_id uuid,
  day date NOT NULL,
  breakfast text,
  lunch text,
  snack text,
  notes text,
  is_public boolean NOT NULL DEFAULT true,
  created_by uuid,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT menus_pkey PRIMARY KEY (id),
  CONSTRAINT menus_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT menus_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id),
  CONSTRAINT menus_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id)
);
CREATE TABLE public.message_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  message_id uuid NOT NULL,
  author_id uuid,
  body text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  edit_history jsonb NOT NULL DEFAULT '[]'::jsonb,
  attachments jsonb NOT NULL DEFAULT '[]'::jsonb,
  deleted_at timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT message_items_pkey PRIMARY KEY (id),
  CONSTRAINT message_items_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id),
  CONSTRAINT message_items_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.messages(id),
  CONSTRAINT message_items_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id)
);
CREATE TABLE public.message_participants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  message_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text,
  unread boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT message_participants_pkey PRIMARY KEY (id),
  CONSTRAINT message_participants_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id),
  CONSTRAINT message_participants_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.messages(id),
  CONSTRAINT message_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  thread_type USER-DEFINED NOT NULL DEFAULT 'dm'::message_thread_type,
  subject text,
  created_by uuid,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id),
  CONSTRAINT messages_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  user_id uuid NOT NULL,
  type text NOT NULL,
  title text NOT NULL,
  body text,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamp with time zone,
  priority text NOT NULL DEFAULT 'normal'::text,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.orgs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  timezone text NOT NULL DEFAULT 'UTC'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT orgs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.photos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  class_id uuid,
  student_id uuid,
  upload_id uuid NOT NULL,
  author_id uuid,
  caption text,
  is_public boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT photos_pkey PRIMARY KEY (id),
  CONSTRAINT photos_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id),
  CONSTRAINT photos_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT photos_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT photos_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES public.uploads(id),
  CONSTRAINT photos_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id)
);
CREATE TABLE public.schema_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  version text NOT NULL UNIQUE,
  applied_at timestamp with time zone NOT NULL DEFAULT now(),
  description text,
  checksum text,
  rollback_sql text,
  CONSTRAINT schema_versions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.staff (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  user_id uuid NOT NULL,
  education_level text,
  union_name text,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT staff_pkey PRIMARY KEY (id),
  CONSTRAINT staff_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id),
  CONSTRAINT staff_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.stories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  class_id uuid,
  author_id uuid,
  title text,
  caption text,
  is_public boolean NOT NULL DEFAULT false,
  expires_at timestamp with time zone NOT NULL,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT stories_pkey PRIMARY KEY (id),
  CONSTRAINT stories_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id),
  CONSTRAINT stories_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT stories_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id)
);
CREATE TABLE public.story_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  story_id uuid NOT NULL,
  upload_id uuid,
  order_index integer NOT NULL DEFAULT 0,
  duration_ms integer,
  caption text,
  mime_type text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  url text,
  CONSTRAINT story_items_pkey PRIMARY KEY (id),
  CONSTRAINT story_items_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES public.uploads(id),
  CONSTRAINT story_items_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id),
  CONSTRAINT story_items_story_id_fkey FOREIGN KEY (story_id) REFERENCES public.stories(id)
);
CREATE TABLE public.student_relatives (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  student_id uuid NOT NULL,
  full_name text NOT NULL,
  relation text,
  phone text,
  email USER-DEFINED,
  notes text,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT student_relatives_pkey PRIMARY KEY (id),
  CONSTRAINT student_relatives_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id),
  CONSTRAINT student_relatives_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.student_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  class_id uuid NOT NULL,
  first_name text NOT NULL,
  last_name text,
  dob date,
  gender USER-DEFINED NOT NULL DEFAULT 'unknown'::gender_type,
  medical_notes text,
  allergies text,
  emergency_contact text,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::student_request_status,
  requested_by uuid NOT NULL,
  approved_by uuid,
  approved_at timestamp with time zone,
  rejected_by uuid,
  rejected_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT student_requests_pkey PRIMARY KEY (id),
  CONSTRAINT student_requests_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id),
  CONSTRAINT student_requests_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT student_requests_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.users(id),
  CONSTRAINT student_requests_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT student_requests_rejected_by_fkey FOREIGN KEY (rejected_by) REFERENCES public.users(id)
);
CREATE TABLE public.students (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  user_id uuid UNIQUE,
  class_id uuid,
  registration_time timestamp with time zone,
  start_date date,
  student_language text,
  barngildi numeric NOT NULL DEFAULT 1.0,
  medical_notes_encrypted text,
  allergies_encrypted text,
  emergency_contact_encrypted text,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT students_pkey PRIMARY KEY (id),
  CONSTRAINT students_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT students_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id),
  CONSTRAINT students_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id)
);
CREATE TABLE public.uploads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  bucket text NOT NULL,
  path text NOT NULL,
  filename text,
  mime_type text,
  size_bytes bigint CHECK (size_bytes IS NULL OR size_bytes >= 0),
  width integer,
  height integer,
  checksum text,
  visibility USER-DEFINED NOT NULL DEFAULT 'private'::upload_visibility,
  created_by uuid,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT uploads_pkey PRIMARY KEY (id),
  CONSTRAINT uploads_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id),
  CONSTRAINT uploads_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  email USER-DEFINED CHECK (email IS NULL OR email ~ '^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$'::citext),
  phone text CHECK (phone IS NULL OR phone ~* '^\+?[1-9]\d{1,14}$'::text AND length(phone) >= 7 AND length(phone) <= 15),
  ssn text,
  address text,
  canlogin boolean NOT NULL DEFAULT true,
  first_name text NOT NULL,
  last_name text,
  role USER-DEFINED,
  bio text,
  avatar_url text,
  gender USER-DEFINED DEFAULT 'unknown'::gender_type,
  last_login_at timestamp with time zone,
  is_active boolean NOT NULL DEFAULT true,
  is_staff boolean NOT NULL DEFAULT true,
  dob date,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  theme text DEFAULT 'system'::text CHECK (theme = ANY (ARRAY['light'::text, 'dark'::text, 'system'::text])),
  language text DEFAULT 'en'::text CHECK (language = ANY (ARRAY['en'::text, 'is'::text])),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id)
);



-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

